# -*- coding: utf-8 -*-
"""Financial_Statements_With_Pivot.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16i7qlCLAzQNgBFXqQhMsm00-_3MRBOsa
"""

import pandas as pd
import numpy as np
import io

from google.colab import files

uploaded = files.upload()

file_name = "FinData.xlsx"

GL = pd.read_excel('FinData.xlsx', sheet_name='GL')
COA = pd.read_excel('FinData.xlsx', sheet_name='COA')
Calendar = pd.read_excel('FinData.xlsx', 'Calendar')
Territory = pd.read_excel('FinData.xlsx', 'Territory')

GL_Master = pd.merge(GL, COA, on='Account_key', how='left').merge(Calendar, on='Date', how='left').merge(Territory, on='Territory_key', how='left')

GL_Master[GL_Master["Report"] == "Profit and Loss"].pivot_table(values="Amount", index="Account_key", columns=["Country", "Year"], aggfunc=sum).style.format(thousands=",", precision=0)

PnL = GL_Master[GL_Master["Report"] == "Profit and Loss"].pivot_table(values='Amount', index=['Class', 'SubClass', 'Account', 'SubAccount', 'Account_key'],
                              columns= 'Year', aggfunc='sum').sort_values("Account_key")

PnL.style.format(thousands=",", precision=0)

Balance_Sheet = GL_Master[GL_Master["Report"] == "Balance Sheet"].pivot_table(values='Amount', index=['Class', 'SubClass', 'Account', 'SubAccount', 'Account_key'],
                              columns= 'Year', aggfunc='sum').cumsum(axis=1).sort_values("Account_key")

Balance_Sheet.style.format(thousands=",", precision=0)

PnL_Countrywise = GL_Master[GL_Master["Report"] == "Profit and Loss"].pivot_table(
    values='Amount',
    index=['Country', 'Class', 'SubClass', 'Account', 'SubAccount', 'Account_key'],
    columns='Year',
    aggfunc='sum'
).sort_values(by=['Country', 'Account_key']).style.format(thousands=",", precision=0)

PnL_Countrywise

pd.set_option('display.max_columns', None)
pd.set_option('display.expand_frame_repr', False)
pd.set_option('display.max_colwidth', None)